USE [master]
GO

/****** Object:  Database [libreria]    Script Date: 12/11/2023 02:09:09 p. m. ******/
CREATE DATABASE [libreria]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'libreria', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\libreria' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'libreria_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\libreria_log' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [libreria].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [libreria] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [libreria] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [libreria] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [libreria] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [libreria] SET ARITHABORT OFF 
GO

ALTER DATABASE [libreria] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [libreria] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [libreria] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [libreria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [libreria] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [libreria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [libreria] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [libreria] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [libreria] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [libreria] SET  DISABLE_BROKER 
GO

ALTER DATABASE [libreria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [libreria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [libreria] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [libreria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [libreria] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [libreria] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [libreria] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [libreria] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [libreria] SET  MULTI_USER 
GO

ALTER DATABASE [libreria] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [libreria] SET DB_CHAINING OFF 
GO

ALTER DATABASE [libreria] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [libreria] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [libreria] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [libreria] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [libreria] SET QUERY_STORE = OFF
GO

ALTER DATABASE [libreria] SET  READ_WRITE 
GO


